export const siteConfig = {
  name: "Omnitech Inc.",
  shortName: "Omnitech",
  tagline: "Shopify Apps That Grow Your Store",
  companyTagline: "Software, Data, & AI Consulting",
  description:
    "Omnitech Inc. designs, builds, and publishes Shopify apps on the App Store—helping merchants automate workflows, save time, and grow their stores.",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://omnitech.dev",
  locale: "en_BD",
  keywords: [
    "Omnitech Inc",
    "Shopify apps",
    "Shopify App Store",
    "Shopify app development",
    "custom software",
    "ecommerce tools",
    "CartLift",
    "AI upsells Shopify",
    "cart drawer upsell",
    "Shopify cross-sell",
    "post-purchase upsell",
  ],
  authors: [{ name: "Omnitech Inc.", url: "https://omnitech.dev" }],
  creator: "Omnitech Inc.",
  publisher: "Omnitech Inc.",
  email: {
    hello: "info@omnitech-inc.com",
    support: "info@omnitech-inc.com",
  },
  company: {
    legalName: "Omnitech, Inc.",
    location: "Tangail, Dhaka, Bangladesh",
    founded: "2026",
    businessHours: "Sunday – Thursday, 9:00 AM – 6:00 PM (BST)",
    phone: {
      display: "+880 1712-345678",
      tel: "+8801712345678",
    },
    headquarters: {
      street: "Tangail Sadar",
      city: "Tangail",
      state: "Dhaka",
      zip: "1900",
      country: "Bangladesh",
    },
    offices: [
      {
        label: "Headquarters",
        street: "Tangail Sadar",
        city: "Tangail",
        state: "Dhaka",
        zip: "1900",
      },
      {
        label: "Dhaka Office",
        street: "Banani",
        city: "Dhaka",
        state: "Dhaka",
        zip: "1213",
      },
    ],
    partners: ["Microsoft Partner", "Shopify App Partner"],
    mainWebsite: "https://www.omnitech-inc.com",
    linkedIn: "https://www.linkedin.com/company/omnitech-inc.",
  },
  social: {
    twitter: "@omnitech",
    linkedIn: "https://www.linkedin.com/company/omnitech-inc.",
  },
};
