export const siteConfig = {
  name: "Omnitech Inc.",
  shortName: "Omnitech",
  tagline: "Shopify Apps Built for Merchants",
  companyTagline: "Software, Data, & AI Consulting",
  description:
    "Omnitech Inc. designs, builds, and publishes Shopify apps on the App Store—helping merchants automate workflows, save time, and grow their stores.",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://omnitech.dev",
  locale: "en_US",
  keywords: [
    "Omnitech Inc",
    "Shopify apps",
    "Shopify App Store",
    "Shopify app development",
    "custom software",
    "ecommerce tools",
    "order notifications",
    "bulk product editor",
    "product reviews",
    "inventory alerts",
  ],
  authors: [{ name: "Omnitech Inc.", url: "https://omnitech.dev" }],
  creator: "Omnitech Inc.",
  publisher: "Omnitech Inc.",
  email: {
    hello: "info@omnitech-inc.com",
    support: "info@omnitech-inc.com",
  },
  company: {
    legalName: "Omnitech, Inc.",
    location: "Sioux Falls, South Dakota, USA",
    founded: "1998",
    businessHours: "Monday – Friday, 8:00 AM – 5:00 PM (CT)",
    phone: {
      display: "(605) 336-0888",
      tel: "+16053360888",
    },
    headquarters: {
      street: "5841 S Corporate Place",
      city: "Sioux Falls",
      state: "SD",
      zip: "57108",
      country: "United States",
    },
    offices: [
      {
        label: "Headquarters",
        street: "5841 S Corporate Place",
        city: "Sioux Falls",
        state: "SD",
        zip: "57108",
      },
      {
        label: "Rapid City Office",
        street: "11 Main Street",
        city: "Rapid City",
        state: "SD",
        zip: "57701",
      },
    ],
    partners: ["Microsoft Partner", "Shopify App Partner"],
    mainWebsite: "https://www.omnitech-inc.com",
    linkedIn: "https://www.linkedin.com/company/omnitech-inc.",
  },
  social: {
    twitter: "@omnitech",
    linkedIn: "https://www.linkedin.com/company/omnitech-inc.",
  },
};
